### PR TITLE
Rename return_buffer option to yield_returns_buffer

### PR DESCRIPTION
**Pull request by evanleck**

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks, this looks good.  Cherry-picked as f3939d1680be34714248e5aba3180aa76dcc3230

**Comment by evanleck** [comment]
I hate to pester, but would you mind cutting a new release if everything looks good to you? Let me know if I can do anything or tidy anything up for ya.

**Comment by jeremyevans** [comment]
Considering the multiple revisions this had to go through, I want to give more time for public review/feedback and potential changes (once it ships, I'm committed to supporting it).  Please ping me again in early December, and unless something has come up I can work on a release then.

**Comment by evanleck** [comment]
Alright, will do. Thanks!

**Comment by evanleck** [comment]
@jeremyevans following up on a possible release for this feature. Do you reckon it's ready to ship or would you like to give it more time?

**Comment by jeremyevans** [comment]
Thanks for the reminder. I think it's a good time to ship.  I'll work on a release shortly.

**Comment by evanleck** [comment]
My pleasure, thanks for getting a release out!

**Pull request closed without merging**
