### PR TITLE
Add `freeze_template_literals` option to avoid String#freeze

### PR DESCRIPTION
**Pull request by casperisfine**
`"foo".freeze` generates an `opt_str_freeze` instruction while `"foo"` when frozen string literals is enabled generated a `putobject` instruction.

The performance difference between the two is not that big, but it's still less work as it doesn't have to check wether String#freeze was redefined.

It also generate much less native code with YJIT.

### CODE REVIEW

**Comment by jeremyevans** [comment]
Tilt also does not correctly support the Erubi `:freeze` option, making it a no-op. Considering 99% of Erubi usage is either from Rails or Tilt, it seems unlikely this optimization will be used.  Worse, using the `:freeze` option to try to enable this optimization would actually deoptimize on Rails/Tilt, since you would be allocating new strings instead of using frozen strings.

I have 5+ year old pull request for underlying frozen string literal support in Tilt: https://github.com/rtomayko/tilt/pull/301. Can you look into whether the `:freeze` option could be enabled in Rails?

If either Tilt and Rails start supporting the `:freeze` option, I would be fine with this change.

**Comment by casperisfine** [comment]
> Can you look into whether the :freeze option could be enabled in Rails?

The only way would be for Rails to look for the magic comment in the generated code and to move it away.

So that's why I said: "Note: I'm not sure if piggy backing on the freeze option makes the most sense."

We may need some kind of `assume_frozen_string_literals` option instead. What do you think?

**Comment by casperisfine** [comment]
Oh, re-reading your comment, you may not be aware of https://github.com/rails/rails/pull/43725. Starting from Rails 7.1 users can enable frozen string literals in templates. We however can't use the Erubi `freeze` option directly.

**Comment by jeremyevans** [comment]
> Oh, re-reading your comment, you may not be aware of [rails/rails#43725](https://github.com/rails/rails/pull/43725). Starting from Rails 7.1 users can enable frozen string literals in templates. We however can't use the Erubi `freeze` option directly.

Correct, I was not aware of that.  I generally do not follow Rails development, especially since I stopped using Rails around 8 years ago.

Since there is a way for Rails to support this, this seems reasonable to support in Erubi. Since `:freeze` causes warnings if you are wrapping the code and not removing the magic comment, I guess a new option would be best. `freeze_template_literals: false` may work as an option name to disable `.freeze` after the literals.  The option value would default to `true` in Ruby 2.1+, and `false` in Ruby < 2.1 (so you could turn it on in Ruby < 2.1 by passing `true` as the value).  Does that sound reasonable to you?

Now that Rails supports frozen string literals in templates, I'll see if I can push Tilt to support it.

**Comment by casperisfine** [comment]
Sounds good. I'll update my PR tomorrow. Thanks for the review!

**Comment by casperisfine** [comment]
PR updated based on your suggestions.

**Comment by jeremyevans** [comment]
Thanks! This looks good.  I'll test and merge shortly.

**Comment by casperisfine** [comment]
Apologies for what I know to be an annoying question, but do you have any plans to cut a new release in near future?

I'd like to integrate this change in Rails, and it would be much easier if I could bump the erubi version requirement.

**Comment by jeremyevans** [comment]
I didn't have plans, but releasing is fairly easy.  I'll try to get a release out tomorrow.

**Comment by jeremyevans** [comment]
Erubi 1.11.0 has been released.

**Comment by byroot** [comment]
Thank you!

**Pull request merged**
